name: build images

on:
  push:
    branches: [ "main" ]
    tags-ignore: [ "*" ]

permissions:
  contents: read
  packages: write

jobs:
  php:
    if: "!contains(github.event.commits[0].message, 'skip:php')"
    timeout-minutes: 30
    runs-on: ubuntu-latest
    name: build base image for php
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        name: login to ghcr.io
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./php/app
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/php:app

  vpn:
    if: "!contains(github.event.commits[0].message, 'skip:vpn')"
    timeout-minutes: 5
    runs-on: ubuntu-latest
    name: build image for openVPN
    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3
      name: login to ghcr.io
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v5
      with:
        context: ./vpn
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/vpn:app

  kubectl:
    if: "!contains(github.event.commits[0].message, 'skip:kubectl')"
    timeout-minutes: 5
    runs-on: ubuntu-latest
    name: build image for kubectl
    env:
      KUBECTL_VERSION: "1.29.1"
    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3
      name: login to ghcr.io
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v5
      with:
        context: ./kubectl
        push: true
        build-args: |
          VERSION=${{ env.KUBECTL_VERSION }}
        tags: ghcr.io/${{ github.repository_owner }}/kubectl,ghcr.io/${{ github.repository_owner }}/kubectl:${{ env.KUBECTL_VERSION }}