name: build images

on:
  push:
    branches: [ "main" ]
    tags-ignore: [ "*" ]

permissions:
  contents: read
  packages: write

jobs:
  fpm:
    if: "!contains(github.event.commits[0].message, 'skip:php')"
    timeout-minutes: 30
    runs-on: ubuntu-latest
    name: build base image for php-fpm
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      name: login to ghcr.io
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v3
      with:
        context: ./php/fpm
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/php:fpm

  php:
    if: "!contains(github.event.commits[0].message, 'skip:php')"
    timeout-minutes: 30
    runs-on: ubuntu-latest
    name: build base image for php-cli
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        name: login to ghcr.io
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: ./php/cli
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/php:cli

  vpn:
    if: "!contains(github.event.commits[0].message, 'skip:vpn')"
    timeout-minutes: 5
    runs-on: ubuntu-latest
    name: build image for openVPN
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      name: login to ghcr.io
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v3
      with:
        context: ./vpn
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/vpn:app

  kubectl:
    if: "!contains(github.event.commits[0].message, 'skip:kubectl')"
    timeout-minutes: 5
    runs-on: ubuntu-latest
    name: build image for kubectl
    env:
      KUBECTL_VERSION: "1.24.4"
      KUBECTL_SHA256: "4a76c70217581ba327f0ad0a0a597c1a02c62222bb80fbfea4f2f5cb63f3e2d8"
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      name: login to ghcr.io
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v3
      with:
        context: ./kubectl
        push: true
        build-args: |
          KUBECTL_VERSION=${{ env.KUBECTL_VERSION }}
          KUBECTL_SHA256=${{ env.KUBECTL_SHA256 }}
        tags: ghcr.io/${{ github.repository_owner }}/kubectl,ghcr.io/${{ github.repository_owner }}/kubectl:${{ env.KUBECTL_VERSION }}
